"""
Integration tests for the GuitarMultiCam pipeline.

These tests use synthetic fixtures generated by tests/fixtures/_generate_fixtures.py.
Run that script once before running these tests:

    python tests/fixtures/_generate_fixtures.py
    pytest tests/test_integration.py

The fixtures encode KNOWN sync offsets so we can validate the sync algorithm
is recovering them correctly within tolerance.
"""

import json
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).parent.parent
FIXTURES = ROOT / "tests" / "fixtures"
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT))


def _ffprobe_json(path: Path) -> dict:
    """Return ffprobe JSON for a media file."""
    result = subprocess.run(
        [
            "ffprobe", "-v", "error",
            "-show_entries", "format=duration:stream=codec_type,codec_name,width,height,r_frame_rate",
            "-of", "json", str(path),
        ],
        capture_output=True, text=True, timeout=10,
    )
    return json.loads(result.stdout) if result.stdout else {}


def _video_stream(probe: dict) -> dict:
    for s in probe.get("streams", []):
        if s.get("codec_type") == "video":
            return s
    return {}


def _has_fixtures() -> bool:
    needed = ["clip_a.mp4", "clip_b.mp4", "clip_c.mp4", "clip_d.mp4", "offsets.json"]
    return all((FIXTURES / n).exists() for n in needed)


pytestmark = pytest.mark.skipif(
    not _has_fixtures(),
    reason="Fixtures missing. Run: python tests/fixtures/_generate_fixtures.py",
)


# ---------------------------------------------------------------------------
# Test 1 — sync recovers known offsets
# ---------------------------------------------------------------------------

def test_sync_offsets_within_tolerance():
    """
    The sync algorithm should recover the known time-shifts injected into
    the synthetic fixtures within the declared tolerance.
    """
    from sync.audio_sync import SyncManager

    truth = json.loads((FIXTURES / "offsets.json").read_text(encoding="utf-8"))
    expected = truth["expected_offsets_vs_clip_a"]
    tolerance = float(truth["tolerance_seconds"])

    clips = [str(FIXTURES / n) for n in expected.keys()]
    result = SyncManager().align_clips(clips)

    # Confidence should be saturated for synthetic clean signals
    assert result.confidence >= 0.95, f"low confidence: {result.confidence}"

    # Compute recovered offsets relative to clip_a, regardless of which clip
    # the algorithm chose as reference
    a_off = result.offsets["clip_a.mp4"]
    recovered = {name: off - a_off for name, off in result.offsets.items()}

    for name, exp_off in expected.items():
        got = recovered[name]
        diff = abs(got - exp_off)
        assert diff <= tolerance, (
            f"{name}: expected {exp_off:+.3f}s, got {got:+.3f}s (diff={diff:.3f}s)"
        )


# ---------------------------------------------------------------------------
# Test 2 — full pipeline 2 clips, 2x1 grid
# ---------------------------------------------------------------------------

def test_pipeline_2clips_grid_2x1(tmp_path):
    """
    Full pipeline (proxy + sync + apply offsets + grid) on 2 fixture clips.
    Output should be a valid 1920x1080 @30fps MP4 with one video and one audio
    stream, and a duration close to the input duration.
    """
    from pipeline import Pipeline, PipelineConfig

    out = tmp_path / "out_2x1.mp4"
    cfg = PipelineConfig(
        clips=[str(FIXTURES / "clip_a.mp4"), str(FIXTURES / "clip_b.mp4")],
        output_path=str(out),
        layout="2x1",
        use_proxy=True,
        proxy_width=320, proxy_height=240,
        output_width=1920, output_height=1080,
        output_fps=30,
        max_workers=2,
    )
    result = Pipeline(cfg).run()

    assert result.get("success"), f"pipeline failed: {result.get('error')}"
    assert out.exists() and out.stat().st_size > 10_000

    probe = _ffprobe_json(out)
    v = _video_stream(probe)
    assert v.get("codec_name") == "h264"
    assert int(v.get("width", 0)) == 1920
    assert int(v.get("height", 0)) == 1080
    # FPS should be 30
    fps_str = v.get("r_frame_rate", "0/1")
    num, den = fps_str.split("/")
    assert abs(float(num) / float(den) - 30.0) < 0.5

    # Duration: should be at least the longest clip (5s) up to clip + max offset (~6.5s)
    duration = float(probe.get("format", {}).get("duration", 0))
    assert 4.5 <= duration <= 8.0, f"unexpected duration: {duration}s"


# ---------------------------------------------------------------------------
# Test 3 — full pipeline 4 clips, 2x2 grid (realistic case)
# ---------------------------------------------------------------------------

def test_pipeline_4clips_grid_2x2(tmp_path):
    """
    Full pipeline with 4 clips into a complete 2x2 grid — the realistic
    production use case for multi-cam guitar performances.
    """
    from pipeline import Pipeline, PipelineConfig

    out = tmp_path / "out_2x2.mp4"
    cfg = PipelineConfig(
        clips=[
            str(FIXTURES / "clip_a.mp4"),
            str(FIXTURES / "clip_b.mp4"),
            str(FIXTURES / "clip_c.mp4"),
            str(FIXTURES / "clip_d.mp4"),
        ],
        output_path=str(out),
        layout="2x2",
        use_proxy=True,
        proxy_width=320, proxy_height=240,
        output_width=1920, output_height=1080,
        output_fps=30,
        max_workers=2,
    )
    result = Pipeline(cfg).run()

    assert result.get("success"), f"pipeline failed: {result.get('error')}"
    assert out.exists() and out.stat().st_size > 10_000

    probe = _ffprobe_json(out)
    v = _video_stream(probe)
    assert int(v.get("width", 0)) == 1920
    assert int(v.get("height", 0)) == 1080
    duration = float(probe.get("format", {}).get("duration", 0))
    assert 4.5 <= duration <= 8.0, f"unexpected duration: {duration}s"
